const actions = {
  FETCHING_BRANDS: "FETCHING_BRANDS",
  FETCHING_BRANDS_SUCCESS: "FETCHING_BRANDS_SUCCESS",
  FETCHING_BRANDS_FAILURE: "FETCHING_BRANDS_FAILURE",
  AUTH_IN_PROGRESS: "AUTH_IN_PROGRESS",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE"
};

export default actions;
