const actions = {
  FETCHING_BRANDS: "FETCHING_BRANDS",
  FETCHING_BRANDS_SUCCESS: "FETCHING_BRANDS_SUCCESS",
  FETCHING_BRANDS_FAILURE: "FETCHING_BRANDS_FAILURE",
  AUTH_IN_PROGRESS: "AUTH_IN_PROGRESS",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE",
  LOGOUT_USER: "LOGOUT_USER",
  FETCHING_COMPONENT_TYPES: "FETCHING_COMPONENT_TYPES",
  FETCHING_COMPONENT_TYPES_SUCCESS: "FETCHING_COMPONENT_TYPES_SUCCESS",
  FETCHING_COMPONENT_TYPES_FAILURE: "FETCHING_COMPONENT_TYPES_FAILURE",
  SEARCH_BAR_TEXT_CHANGED: "SEARCH_BAR_TEXT_CHANGED",
  BRAND_SELECTION_CHANGED: "BRAND_SELECTION_CHANGED",
  COMPONENT_TYPE_SELECTION_CHANGED: "COMPONENT_TYPE_SELECTION_CHANGED",
  PAGE_CHANGED: "PAGE_CHANGED",
  PAGE_SIZE_CHANGED: "PAGE_SIZE_CHANGED",
  FETCHING_COMPONENTS: "FETCHING_COMPONENTS",
  FETCHING_COMPONENTS_SUCCESS: "FETCHING_COMPONENTS_SUCCESS",
  FETCHING_COMPONENTS_FAILURE: "FETCHING_COMPONENTS_FAILURE",
  FETCHING_ONE_COMPONENT: "FETCHING_ONE_COMPONENT",
  FETCHING_ONE_COMPONENT_SUCCESS: "FETCHING_ONE_COMPONENT_SUCCESS",
  FETCHING_ONE_COMPONENT_FAILURE: "FETCHING_ONE_COMPONENT_FAILURE",
  SELECTED_NAVIGATION_COMPONENT_CHANGED: "SELECTED_NAVIGATION_COMPONENT_CHANGED"
};

export default actions;
